name: Sync Upstream

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # Trigger manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: Abirdcfly
          base: master
          head: master
          auto_merge: 'false'
          pr_title: Sync with hyperledger-labs/fabric-operator
          pr_message: If there is a conflict, it is recommended to manually merge the conflicting commits, and then manually execute the sync github action.
